package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloApp.idl
* Thursday, March 7, 2019 11:10:53 PM CST
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
