/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PA1_H_RPCGEN
#define _PA1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define TIME_PROG 0x2345111
#define TIME_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define get_server_time 1
extern  char ** get_server_time_1(void *, CLIENT *);
extern  char ** get_server_time_1_svc(void *, struct svc_req *);
extern int time_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_server_time 1
extern  char ** get_server_time_1();
extern  char ** get_server_time_1_svc();
extern int time_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PA1_H_RPCGEN */
