package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloApp.idl
* Thursday, March 7, 2019 9:21:34 PM CST
*/

public interface HelloOperations 
{
  String hellomessage ();
  void hellomessage (String newHellomessage);
} // interface HelloOperations
