/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pa1.h"
int get_response();

void
pa1_prog_1(char *host, int request)
{
	CLIENT *clnt;
	char * *result_1;
	int  get_server_response_1_arg = request;

#ifndef	DEBUG
	clnt = clnt_create (host, PA1_PROG, PA1_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = get_server_response_1(&get_server_response_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("### RESULT FROM SERVER: \n%s\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int menu_choice = 0;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	while(1)
	{
		menu_choice = get_response();
		if(menu_choice == 7){ break; }
		printf("                Menu_choice: %d\n\n\n", menu_choice);
		pa1_prog_1 (host, menu_choice);
	}
	
exit (0);
}


int get_response()
{    
	int choice;    
	printf("===========================================\n");    
	printf("                   Menu: \n");    
	printf("-------------------------------------------\n");    
	printf("                1. Server Time\n");    
	printf("                2. CPU Usage\n");    
	printf("                3. Memory Usage\n");    
	printf("                4. Swap Usage\n");    
	printf("                5. List of User Names\n");   
	printf("                6. Load Procs Per Min\n");   
	printf("                7. Quit\n");   
	printf("-------------------------------------------\n");    
	printf("               Choice (1-7):");    
	scanf("%d",&choice);    
	printf("===========================================\n");    
	return choice;
}