package AuctionApp;


/**
* AuctionApp/Auction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Friday, March 8, 2019 9:19:17 PM CST
*/

public interface Auction extends AuctionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Auction
