package AuctionApp;


/**
* AuctionApp/AuctionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Friday, March 8, 2019 9:19:17 PM CST
*/

public interface AuctionOperations 
{
  String offer_item (AuctionApp.Item item);
  String sell (String userID);
  String bid (String userID, String price);
  String view_high_bidder (String userID);
  String view_bid_status (String userID);
  String view_auction_status (String userID);
} // interface AuctionOperations
