package AuctionApp;


/**
* AuctionApp/Item.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Friday, March 8, 2019 9:19:17 PM CST
*/

public final class Item implements org.omg.CORBA.portable.IDLEntity
{
  public String seller = null;
  public String itemDescr = null;
  public String iniPrice = null;

  public Item ()
  {
  } // ctor

  public Item (String _seller, String _itemDescr, String _iniPrice)
  {
    seller = _seller;
    itemDescr = _itemDescr;
    iniPrice = _iniPrice;
  } // ctor

} // class Item
